matrix:
  include:
    - os: linux
      language: node_js
      node_js: "6"
      env:
        - TRAVIS=true
    - os: linux
      language: node_js
      node_js: "8"
      env:
cache:
  yarn: true
  directories:
    - "node_modules"
script:
  - yarn run test:ci
