matrix:
  include:
    - os: linux
      language: node_js
      node_js: "6"
    - os: linux
      language: node_js
      node_js: "8"
cache:
  yarn: true
  directories:
    - "node_modules"
script:
  - yarn run test:ci
